export const ACTIONS = {
    SET_USER_DATA: 'cards/profile/SET_USER_DATA',
    SET_AUTH_STATUS: 'cards/login/SET_AUTH_STATUS',
    SET_LOGIN_STATUS: 'cards/login/SET_LOGIN_STATUS',
    SET_LOGIN_ERROR: 'cards/login/SET_LOGIN_ERROR',
    SET_REGISTER_STATUS: 'cards/login/SET_REGISTER_STATUS',
    SET_REGISTER_ERROR: 'cards/register/SET_REGISTER_ERROR',
    SET_PACKS_DATA: 'cards/packs/SET_PACKS_DATA',
    SET_CURRENT_PAGE: 'cards/packs/SET_CURRENT_PAGE',
    SET_SEARCH_STRING: 'cards/packs/SET_SEARCH_STRING',
    SET_PACKS_STATUS: 'cards/packs/SET_PACKS_STATUS',
}